<?php

namespace CalculatorBundle\Repository;

/**
 * CalculatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalculatorRepository extends \Doctrine\ORM\EntityRepository
{
}
